# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: admin@whisperlab.com
  admin_password: 6wSV8D7iX5
  domain_name: example.com
  secret_key_base: e94edd74b31f13336c807ce56a046ef712464274b51d39d38ebde734e0f6b913abfb0cdeb9114c177cd011cdca226efcc3b575753b882cfda41cfab1f214fd37

test:
  domain_name: example.com
  secret_key_base: c28f30534570f51b71ac35aff3ba031497dc7116a0d5c495409ecd4e87cf15e34acefc828de09ac978271c0ba0a921759463399463829ef09ec3e77dab43fbce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
